version: '3.6'

services:
  bot:
    image: f213/selfmailbot
    restart: always
    command: python -m srv.app
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    env_file:
      .env

    links:
      - redis

  celery-worker:
    image: f213/selfmailbot
    restart: always
    command: celery -A srv.celery worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    env_file:
      .env

    links:
      - redis

  celery-flower:
    image: f213/selfmailbot
    restart: always
    command: celery -A srv.celery flower --url-prefix=flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

    links:
      - redis

  confirmation-webapp:
    image: f213/selfmailbot
    restart: always
    command: uwsgi --http :8000 --module srv.web:app --workers 2 --threads 2
    env_file:
      .env

  redis:
    image: redis:4-alpine

  nginx-routing:
    image: nginx
    volumes:
      - ./infra/nginx-routing.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - confirmation-webapp
      - celery-flower